


apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: argo-nodepool
spec:
  template:
    metadata:
      labels:
        environment: argo
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws  
        kind: EC2NodeClass
        name: test-node-class

      #expireAfter: 720h | Never
 
      #terminationGracePeriod: 48h 

      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
          minValues: 2
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["m5","m5d","c5","c5d","c4","r4"]
          minValues: 5
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-1a", "us-east-1b"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]

  
