
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: test-node-class
spec:
  amiFamily: AL2023
  associatePublicIPAddress: true

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "poc-cluster"

  amiSelectorTerms:
    #- id: ami-03c7095f7c9fd69d3
    - alias: al2023@v20241106

  securityGroupSelectorTerms:
    #- name: eks-cluster-sg-poc-cluster-588438671
    - tags:
        karpenter.sh/discovery: "poc-cluster"
        
  #role: "KarpenterNodeRole-poc-cluster"

  instanceProfile: KarpenterNodeInstanceProfile-poc-cluster


  

  