apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
  - repo: https://charts.fairwinds.com/stable
    name: goldilocks
    releaseName: goldilocks
    valuesFile: values.yaml
